### ISSUE TITLE
Unable to install with 6.1 on Homestead

### ISSUE THREAD

**Issue by joeycoonce** [PrinsFrank/IndentingPersistentBladeCompiler#1]
I'm working in a pretty basic 6.1 installation, (composer.json is set to ^6.0) which was updated immediately prior to attempting to install the IndentingPersistentBladeCompiler package.
When I attempt to run the provided install command `composer require prinsfrank/indenting-persistent-blade-comp`, I get the 'Installation failed' error:

Here is the full output. Any thoughts?
Thanks!

> Using version ^1.0 for prinsfrank/indenting-persistent-blade-compiler
> 
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: remove laravel/framework v6.1.0
>     - Conclusion: don't install laravel/framework v6.1.0
>     - prinsfrank/indenting-persistent-blade-compiler v1.0.0 requires illuminate/view ^5.8 -> satisfiable by illuminate/view[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
>     - prinsfrank/indenting-persistent-blade-compiler v1.0.1 requires illuminate/view ^5.8 -> satisfiable by illuminate/view[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
>     - prinsfrank/indenting-persistent-blade-compiler v1.0.2 requires illuminate/view ^5.8 -> satisfiable by illuminate/view[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
>     - don't install illuminate/view 5.8.x-dev|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.0|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.11|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.12|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.14|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.15|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.17|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.18|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.19|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.2|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.20|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.22|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.24|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.27|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.28|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.29|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.3|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.30|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.31|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.32|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.33|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.34|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.35|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.4|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.8|don't install laravel/framework v6.1.0
>     - don't install illuminate/view v5.8.9|don't install laravel/framework v6.1.0
>     - Installation request for laravel/framework (locked at v6.1.0, required as ^6.0) -> satisfiable by laravel/framework[v6.1.0].
>     - Installation request for prinsfrank/indenting-persistent-blade-compiler ^1.0 -> satisfiable by prinsfrank/indenting-persistent-blade-compiler[v1.0.0, v1.0.1, v1.0.2].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by joeycoonce** [comment]
Any idea?

**Comment by PrinsFrank** [comment]
Hey @joeycoonce,

Sorry for my late response, i missed the notification for this issue. I just updated the composer version constraints to include the recent releases of Laravel. This has just been merged in #2. You should now be able to require this package with the latest releases! Let me know if you have any problems!

**Comment by joeycoonce** [comment]
Fantastic, thanks!
